### ISSUE TITLE
About published information

### ISSUE THREAD

**Issue by homio13** [priya-dwivedi/chat-with-code#2]
https://github.com/priya-dwivedi/chat-with-code/blob/680c4d8d4c547550b5978db5306a431773b15d56/chatbot.py#L17
https://github.com/priya-dwivedi/chat-with-code/blob/680c4d8d4c547550b5978db5306a431773b15d56/utils.py#L27

Thanks for the useful information.
I was just wondering if it's not a good idea to make this information public.

**Comment by priya-dwivedi** [comment]
No it wasn't :(
Bad mistake. No longer on main and this key was deactivated.
